name: Code Formating

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  imports-check-isort:
    name: Check valid import formatting with isort
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort torchdetect tests --check --diff
  code-format-black:
    name: Check code formatting with Black
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install Black
      - name: Run Black
        run: black --config pyproject.toml torchdetec tests --check
  type-checking-mypy:
    name: Type checking with mypy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy --config-file .mypy.ini -p torchdetect
  check-format-yamllint:
    name: Check YAML format with yamllint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint -c .yamllint.yaml conf
